name: order_book
description: A new Flutter package project.
publish_to: 'none'
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  decimal: any
  uuid: any
  json_annotation: ^4.8.1
  flutter_bloc: any
  freezed_annotation: ^2.4.1
  collection: ^1.17.1
  declarative_animated_list: ^0.2.0
  either_dart: ^1.0.0
  freezed: ^2.4.5
  visiblity_manager:
    path: /Users/airm1/work/visiblity_manager/visiblity_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.5.4

flutter:


